sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
addons:
  firefox: latest
  chrome: stable
before_install:
  - mkdir travis-bin
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz -O $PWD/travis-bin/geckodriver-v0.26.0-linux64.tar.gz
  - wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip -O $PWD/travis-bin/chromedriver_linux64.zip
  - tar -xvf $PWD/travis-bin/geckodriver-v0.26.0-linux64.tar.gz -C $PWD/travis-bin
  - unzip $PWD/travis-bin/chromedriver_linux64.zip -d $PWD/travis-bin
  - export PATH=$PWD/travis-bin:$PATH
#  - ls -l $PWD/travis-bin
#  - chromedriver --version
#  - geckodriver --version
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
install: true
script: mvn clean verify